# (可选)全局 监听地址。默认 127.0.0.1
# 默认 127.0.0.1
HOST: 127.0.0.1
# (可选)全局 监听端口。默认 8000
# 默认 8000
PORT: 8000


### 数据库, 兼容 mariadb & mysql
DB:
  # 数据库地址
  host: "10.0.0.111"
  # 数据库端口
  port: "3306"
  # 数据库名称
  db: "sms"
  # 数据库账号
  user: "sms"
  # 数据库密码
  password: "sms"
  # 数据库编码, 默认就行
  charset: "utf8mb4"


### Gotify推送
Gotify:
  url: "114.51.41.91:19810"
  token: "sms"